config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pokemons#index'
  resources :pokemons
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pokemon.rb
class Pokemon < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController

  def index
    @pokemons = Pokemon.all
  end
  
  def new
    @pokemon = Pokemon.new
  end

  def create
    @pokemon = Pokemon.new(pokemon_params)
    @pokemon.save
    
    redirect_to pokemons_path
  end

  def show
    set_pokemon
  end

  def edit
    set_pokemon
  end

  def update
    set_pokemon
    @pokemon.update(pokemon_params)
  end

  def destroy
    set_pokemon
    @pokemon.destroy

    redirect_to pokemons_path
  end

  private

  def pokemon_params
    params.require(:pokemon).permit(:name, :description, :image)
  end

  def set_pokemon
    @pokemon = Pokemon.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pokemons_helper.rb
module PokemonsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pokedex</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
    <div class="bg-img">
      <%= render 'nav_pokemons'%>
      <div class="container">
        <%= yield %>
      </div>
    </div> 
  </body>
</html>

app/views/pokemons/_form_pokemon.html.erb
<div class="pt-2">
  <%= form_for @pokemon do |f|%>
    <div class="form-group">
    <%= f.label :name, class:"form-label text-label"%>
    <%= f.text_field :name, class:"form-control"%>
    </div>
    <div class="form-group mt-3">
    <%= f.label :description, class:"form-label text-label"%>
    <%= f.text_field :description, class:"form-control"%>
    </div>
    <div class="form-group mt-3">
    <%= f.label :image, class:"form-label text-label"%>
    <%= f.text_field :image, class:"form-control"%>
    </div>

    <div class="flex">
      <%= f.submit :Add, class:"btn btn-success mt-2 paddings"%>
      <%= link_to "Back", pokemons_path, class:"btn btn-secondary mt-2 paddings"%>
    </div>
  <% end %>
</div>

app/views/pokemons/_nav_pokemons.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%# <a class="navbar-brand" href="#">POKEMONS</a> %>
    <%= link_to "POKEMONS", pokemons_path, class:"navbar-brand"%>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/pokemons/new">Add pokemon</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Link</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/pokemons/edit.html.erb
<div class="mt-5 bg-light bg-gradient rounded p-3">
  <h1 class="text-center">Edit the pokemon!</h1>
  <%= render 'form_pokemon' %>
</div>

app/views/pokemons/index.html.erb
<h1 class="text-center">¡POKEMONS!</h1>
<div class="pokemons">
  <% @pokemons.each.with_index do |pokemon, index| %>
    <div class="pokemones">
      <%= index + 1 %> - 
      <%= pokemon.name %> 
    </div>
    <div class="toolbar">
      <%= link_to "Ver Pokemon", pokemon_path(pokemon), class:"btn btn-secondary"%>
      <%= link_to "Editar Pokemon", edit_pokemon_path(pokemon), class:"btn btn-primary"%>
    </div>
  <% end %>
</div>

app/views/pokemons/new.html.erb
<div class="mt-5 bg-light bg-gradient rounded p-3">
  <h1 class="text-center">New pokemon!</h1>
  <%= render 'form_pokemon' %>
</div>

app/views/pokemons/show.html.erb
<div class="container d-flex flex-column bg-light rounded mt-2">
  <p class="text-center mt-3 fs-1"><%= @pokemon.name %></p>
  <img src="<%= @pokemon.image%>" class="img_fluid mx-auto">
  <p class="text-center mt-3 fs-3"><%=@pokemon.description%></p>
  <div class="show mb-2">
    <%=link_to "Back", pokemons_path, class:"btn btn-primary"%>
    <%= link_to "Delete", pokemon_path(@pokemon), method: :delete, class:"btn btn-warning"%>
  </div>
</div>